'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("draft.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _8_bit_Remix__Animal_Crossing___Bubblegum_K_K___Aircheck_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_8_bit_Remix__Animal_Crossing___Bubblegum_K_K___Aircheck_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property A_Lonely_Cherry_Tree() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("A_Lonely_Cherry_Tree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Chill_Chiptune___Late_Night_Lights_by_RyanAvx__Relaxing_lofi_8_Bit_music_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Chill_Chiptune___Late_Night_Lights_by_RyanAvx__Relaxing_lofi_8_Bit_music_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Come_Along_With_Me__Island_Song___8_Bit_Tribute_to_Adventure_Time___Ashley_Eriksson_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Come_Along_With_Me__Island_Song___8_Bit_Tribute_to_Adventure_Time___Ashley_Erikss"& _ 
                        "on_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Dragon_ball_Super___Ultra_Instinct__8_bit_Cover_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Dragon_ball_Super___Ultra_Instinct__8_bit_Cover_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loading_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Onepunch_Man___The_Hero_FULL__8bit_mix_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Onepunch_Man___The_Hero_FULL__8bit_mix_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Prayer_In_C__8_Bit_Remix_Cover_Version____Koi_Dance_Touhou_8_Bit_Universe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Prayer_In_C__8_Bit_Remix_Cover_Version____Koi_Dance_Touhou_8_Bit_Universe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Rugrats_Theme__8_Bit_Tribute_to_Rugrats____8_Bit_Universe_1_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Rugrats_Theme__8_Bit_Tribute_to_Rugrats____8_Bit_Universe_1_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SPARKLE() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SPARKLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Steven_Universe_theme_in_8_bit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Steven_Universe_theme_in_8_bit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property 前前前世君の名は_8bit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("前前前世君の名は_8bit", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
